### ISSUE TITLE
NEO4J build software does not work with the latest version of the py2neo library, py2neo 4.x

### ISSUE THREAD

**Issue by jayped007** [IHTSDO/snomed-database-loader#30]
Currently, it is necessarily to use version 3.1.2 of the py2neo library for use in the NEO4J database build.  However, the current version of py2neo is version 4.  The build currently fails if attempted with version 4 of the py2neo library which is what is installed by default when installing py2neo.

**Comment by kaicode** [comment]
Fixed by pull request #29
