### ISSUE TITLE
ERROR 1148 

### ISSUE THREAD

**Issue by harshsharma09** [IHTSDO/snomed-database-loader#32]
Need you help!

When i executed this query i got;
ERROR 1148: The used command is not allowed with this MySQL version. I tried changing Infile settings on client and server both. Still the same error. Now, i have to manually convert excel into csv and then upload for each table. Its is taking almost 20 hours for each import.

I am using MySQL 8

**Comment by harshsharma09** [comment]
Hi @pgwilliams Thanks for your help. Happy New Year 2019. 
I tried your solution. It is shows 'ON" when execute command SHOW GLOBAL VARIABLES LIKE 'local_infile';
However, when i am running the query in MySQL workbench its gives the same error 1148. 
Really no idea what to do....i have multiple tables with almost 4 million records each. Takes days to do it manually.

**Comment by pgwilliams** [comment]
Happy New Year to you too @harshsharma09 

I'll try to reproduce this issue and work through it from there.   What operating system are you using?  Thanks, Peter

**Comment by harshsharma09** [comment]
HI @pgwilliams i am working on 64 bit Windows 7 Enterprise.

**Comment by kaicode** [comment]
Closing this issue as it's very old. Please reopen if it's still a problem.

**Comment by hsharma09** [comment]
Thank you, Kai, for the notification.
