### ISSUE TITLE
Neo4J import 7-2019 release

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snomed-database-loader#34]
Hi all,

Regarding Neo4J/SNOMED: I wanted to give this a go for a demo involving visualization of patient cohorts - but quickly ran into issues.
Running an import stalls on 'FIND_ROLENAMES'. I am running python 3.7.4 and py2neo 3.1.2. The code is executed in a WSL console, and the script does connect to my local Neo4J desktop server.
I have tried python 2.7 & 3.6 without any luck, same results.
Perhaps anyone can help me or point me in the right direction!

Best regards,
Sander

Console output:
`rm /var/tmp/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z -R && \
mkdir /var/tmp/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z && 
python snomed_g_graphdb_build_tools.py db_build --release_type full --mode build --action create --rf2 /c/Users/[]/Documents/Snomed\ release/dir/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z/Full/ --release_type full --neopw snomed --output_dir /var/tmp/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z
SNOMED_G bin directory [/c/Users/[]/Documents/development/SNOMED-CT-Database/NEO4J/]
sequence did not exist, primed
JOB_START
FIND_ROLENAMES
FAILED (steps: ['FIND_ROLENAMES'])`

[build.log](https://github.com/IHTSDO/snomed-database-loader/files/3685596/build.log)

**Comment by pgwilliams** [comment]
Hi @mertenssander I'm afraid SNOMED International hasn't had a hand in this code to date; we took it as a generous donation from University of Nebraska.   I wonder if the original author @jayped007 is able to look into your issue...

**Comment by jayped007** [comment]
Hi,
I should be able to help with this issue.  Can you send email to jay.pedersen@unmc.edu?
I think that there should be a log file to help with the debugging.  I would guess that you are running into something that I have seen before.
I know that the program writes to a log file as it moves though its processing steps.  That is the next thing we should look at.
By default, the log file name is "build.log" in the output directory.  That is what I would like to see first.  The --logfile qualifier allows you to give it a different name, but I am guessing you have build.log.
Thanks!

Jay Pedersen
    On Thursday, October 3, 2019, 6:32:13 AM CDT, Peter G. Williams <notifications@github.com> wrote:  
 
 
Hi @mertenssander I'm afraid SNOMED International hasn't had a hand in this code to date; we took it as a generous donation from University of Nebraska. I wonder if the original author @jayped007 is able to look into your issue...

**Comment by mertenssander** [comment]
Thank you for your reply @jayped007 !
I will send you an email for further communication, and post back in this thread if we find a solution.
Perhaps you missed this (it is not very noticeable), but I did include the build.log file in my initial post, at the  bottom of the post!

**Comment by mertenssander** [comment]
Hi all,

Many thanks to @jayped007 for confirming that this code does in fact function correctly with the latest release!

After adding many debug outputs to the scripts, I found that the script would hang on the file path to the release.
Windows Subsystem for Linux often shows some strange behaviour, and in this case, the filepath `/c/Users/$USER/Documents/Snomed\ release/dir/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z/Full/ `
Broke on the \ in the `Snomed\ release` folder. I figured this out by forcing https://github.com/IHTSDO/snomed-database-loader/blob/f6914bf7d5c840738e67489a605cec400b0afe4d/NEO4J/snomed_g_rf2_tools.py#L869 to output opts.rf2 -> It contained the path `/c/Users/$USER/Documents/Snomed`.

This lead to the script progressing to the EXECUTE_CYPHER phase, but quitting there.
After a lot of research, I found that the debug log from Neo4J states that it cannot find the CSV files (`file:/c/Users/[******]/Documents/SnomedRelease/neo4jbuild/concept_new.csv`). This is, of course, totally understandable, since Neo4J is running as a Windows application with Windows paths.....
A test with manually editted Windows formatted pathsin the CYPHER commands lead to success; `file:///C:\\Users\\[*******]\\Documents\\SnomedRelease\\neo4jbuild\\concept_new.csv`
I guess I need to run the script under Windows instead of WSL, or host Neo4J in a docker container.

I hope this helps someone - my quest continues but there is light at the end of the tunnel.
Thanks again for getting me started @jayped007 !

**Comment by mertenssander** [comment]
Update: great success. Installing py2neo==3.1.2 and python==3.7.0 under windows solved it all.
