### ISSUE TITLE
Issue of "sequence did not exist, primed" in SNOMED_G tool

### ISSUE THREAD

**Issue by aushikun** [IHTSDO/snomed-database-loader#37]
Hello,

I am trying SNOMED_G tool, since I don't have a strong IT background and encountered the issue as below:
I ran this command:

python ./prog/snomed_g_graphdb_build_tools.py db_build --action create --rf2 ./SCT_RF2_201801/ --release_type full --release_type full --neopw64 1234 --output_dir ./output/ --language_code 'en-us' --language_name 'USEnglish'

I got the reponse like this:

SNOMED_G bin directory [/Users/wangzhi/Program-test/Neo4j/Snomed_Neo/prog/]
sequence did not exist, primed
JOB_START
FIND_ROLENAMES
FAILED (steps: ['FIND_ROLENAMES'])

I am using:
1. Python2.7 and Py2neo 4.3.0 on a mac;
2. I wanted to try to convert the SNOMED CT of version 201801 to Neo4j format;
[build.log](https://github.com/IHTSDO/snomed-database-loader/files/4116221/build.log)

I don't know how to solve this problem. Is there anyone who can help me? :)

**Comment by aushikun** [comment]
Hi everyone:

I got the reply from Jay and I have a directory of "./SCT_RF2_201801/Full/Terminology” and set the parameter like "--rf2 ./SCT_RF2_201801/Full/“.
I also uninstalled py2neo 4.3.0 in python 2.7 and run “pip install py2neo==3.1.2” successfully.

And then, I ran the following command:

python ./prog/snomed_g_graphdb_build_tools.py db_build --action create --rf2 ./SCT_RF2_201801/Full/ --release_type full --neopw64 1234 --output_dir ./output --language_code 'en-us' --language_name ‘USEnglish'

I got the following error message:

SNOMED_G bin directory [/Users/wangzhi/Program-test/Neo4j/Snomed_Neo/prog/]
Traceback (most recent call last):
  File "./prog/snomed_g_graphdb_build_tools.py", line 328, in <module>
    parse_and_interpret(sys.argv[1:]) # causes sub-command processing to occur as well
  File "./prog/snomed_g_graphdb_build_tools.py", line 325, in parse_and_interpret
    command_interpreters[command_index][1](arglist[1:]) # call appropriate interpreter
  File "./prog/snomed_g_graphdb_build_tools.py", line 198, in db_build
    if opts.mode=='build': neo4j = snomed_g_lib_neo4j.Neo4j_Access(base64.decodestring(opts.neopw64))
  File "/Users/wangzhi/Program-test/Neo4j/Snomed_Neo/prog/snomed_g_lib_neo4j.py", line 15, in __init__
    self.graph_db = py2neo.Graph(password=base64pw) # 'http://localhost:7474/db/data/transaction/commit'
  File "/Library/Python/2.7/site-packages/py2neo/database/__init__.py", line 327, in __new__
    use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
  File "/Library/Python/2.7/site-packages/py2neo/database/http.py", line 151, in get
    headers = dict(self.headers, **(headers or {}))
  File "/Library/Python/2.7/site-packages/py2neo/database/http.py", line 110, in headers
    headers = get_http_headers(self.__uri__.scheme, self.__uri__.host, self.__uri__.port)
  File "/Library/Python/2.7/site-packages/py2neo/database/http.py", line 70, in get_http_headers
    uri_headers["Authorization"] = auth.http_authorization
  File "/Library/Python/2.7/site-packages/py2neo/database/auth.py", line 156, in http_authorization
    self.password).encode("UTF-8")).decode("ASCII")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 6: ordinal not in range(128)

I am not so familiar with python, I guess it might be the problem of unicode in the file of auth.py.
I checked the log file, which is empty.

**Comment by kaicode** [comment]
Closing this issue as it's very old. Please reopen if it's still a problem.
