### ISSUE TITLE
Error with make_description_csvs

### ISSUE THREAD

**Issue by erichills** [IHTSDO/snomed-database-loader#43]
count of RF2 ids: 481176
count of FSNs in RF2: 481176
Total RF2 elements: 481176, NEW: 481176, CHANGE: 0, NO CHANGE: 0
0000_make_concept_csvs              : 0:00:10.400222
0001_read_RF2_description           : 0:00:04.058203
0002_read_RF2_concept               : 0:00:01.983312
0003_generate_csvs                  : 0:00:03.799919
count of RF2 ids: 1498107
Traceback (most recent call last):
  File "/home/erica//snomed_g_rf2_tools.py", line 1188, in <module>
    parse_and_interpret(sys.argv[1:]) # causes sub-command processing to occur as well
  File "/home/erica//snomed_g_rf2_tools.py", line 1185, in parse_and_interpret
    command_interpreters[command_index][1](arglist[1:]) # call appropriate interpreter
  File "/home/erica//snomed_g_rf2_tools.py", line 771, in make_csv
    elif opts.element=='description':  make_description_csvs()
  File "/home/erica//snomed_g_rf2_tools.py", line 342, in make_description_csvs
    snomed_g_lib_rf2.Process_Rf2_Release_File( rf2_filename('language') ).process_file(language_cb, None, require_active=False)
  File "/home/erica/snomed_g_lib_rf2.py", line 184, in process_file
    callback_rtn(fields, self.fields_d, []) # history is 3rd arg
  File "/home/erica//snomed_g_rf2_tools.py", line 315, in language_cb
    id = fields[ fields_d['referencedComponentId'] ] # DONT USE "id", use the id associated with the Description
IndexError: list index out of range
JOB_START
FIND_ROLENAMES
python /home/erica//snomed_g_rf2_tools.py find_rolenames --release_type full --rf2 /home/erica/SNOMED_US/ --language_code en --language_name Language
FIND_ROLEGROUPS
python /home/erica//snomed_g_rf2_tools.py find_rolegroups --release_type full --rf2 /home/erica/SNOMED_US/ --language_code en --language_name Language
MAKE_CONCEPT_CSVS
python /home/erica//snomed_g_rf2_tools.py make_csv --element concept --release_type full --rf2 /home/erica/SNOMED_US/ --neopw eric3196 --action create --relationship_file Relationship --language_code en --language_name Language
MAKE_DESCRIPTION_CSVS
python /home/erica//snomed_g_rf2_tools.py make_csv --element description --release_type full --rf2 /home/erica/SNOMED_US/ --neopw eric3196 --action create --relationship_file Relationship --language_code en --language_name Language

FAILED (steps: ['MAKE_DESCRIPTION_CSVS'])

SUMMARY:

JOB_START                 : SUCCESS                  , duration:0:00:00.000051
FIND_ROLENAMES            : SUCCESS                  , duration:0:00:10.935449
FIND_ROLEGROUPS           : SUCCESS                  , duration:0:00:09.504898
MAKE_CONCEPT_CSVS         : SUCCESS                  , duration:0:00:10.996589
MAKE_DESCRIPTION_CSVS     : FAILED (STATUS 1)        , duration:0:00:15.544709

DETAILS:

Backup sequence number: 1
step:[JOB_START],result:[SUCCESS],command:[None],status/expected:0/0,duration:0:00:00.000051,output:[JOB-START(action:[create], mode:[build], release_type:[full], rf2:[/home/erica/SNOMED_US/], date:[20200701])],error:[],cmd_start:[2020-07-01 23:57:04.065075],cmd_end:[2020-07-01 23:57:04.065126]
step:[FIND_ROLENAMES],result:[SUCCESS],command:[python /home/erica//snomed_g_rf2_tools.py find_rolenames --release_type full --rf2 /home/erica/SNOMED_US/ --language_code en --language_name Language],status/expected:0/0,duration:0:00:10.935449,output:[],error:[],cmd_start:[2020-07-01 23:57:04.065138],cmd_end:[2020-07-01 23:57:15.000587]
step:[FIND_ROLEGROUPS],result:[SUCCESS],command:[python /home/erica//snomed_g_rf2_tools.py find_rolegroups --release_type full --rf2 /home/erica/SNOMED_US/ --language_code en --language_name Language],status/expected:0/0,duration:0:00:09.504898,output:[],error:[],cmd_start:[2020-07-01 23:57:15.000635],cmd_end:[2020-07-01 23:57:24.505533]
step:[MAKE_CONCEPT_CSVS],result:[SUCCESS],command:[python /home/erica//snomed_g_rf2_tools.py make_csv --element concept --release_type full --rf2 /home/erica/SNOMED_US/ --neopw eric3196 --action create --relationship_file Relationship --language_code en --language_name Language],status/expected:0/0,duration:0:00:10.996589,output:[],error:[],cmd_start:[2020-07-01 23:57:24.505590],cmd_end:[2020-07-01 23:57:35.502179]
step:[MAKE_DESCRIPTION_CSVS],result:[FAILED (STATUS 1)],command:[python /home/erica//snomed_g_rf2_tools.py make_csv --element description --release_type full --rf2 /home/erica/SNOMED_US/ --neopw eric3196 --action create --relationship_file Relationship --language_code en --language_name Language],status/expected:1/0,duration:0:00:15.544709,output:[],error:[],cmd_start:[2020-07-01 23:57:35.502236],cmd_end:[2020-07-01 23:57:51.046945]

Hello, I am having an issue with an IndexError with the header of either the language or description files. I have tried editing the headers and reformatting data columns but nothing seems to work. I am also not sure what id the following comment is referring to: id = fields[ fields_d['referencedComponentId'] ] # DONT USE "id", use the id associated with the Description.

Thanks

**Comment by kaicode** [comment]
Closing this issue as it's very old. Please reopen if it's still a problem.
