### ISSUE TITLE
Could you please give some idea on how to access SnomedCT_RF2Release_INT_xxxx.zip file

### ISSUE THREAD

**Issue by tyuanhang** [IHTSDO/snomed-database-loader#44]

**Comment by uklft** [comment]
For the international version you can visit the [Snomed page](https://www.nlm.nih.gov/healthit/snomedct/international.html) of the US National Library of Medicine. From there you will be directed to create a login at https://utslogin.nlm.nih.gov/ an request a license for the Snomed-CT.

Or did you mean how to use the files in the archive?

**Comment by kaicode** [comment]
Access SNOMED CT RF2 release files: [Get SNOMED CT](https://snomed.org/get-snomed).
