### ISSUE TITLE
snomed_g_TC_tools.py NEO4J DB build version 1.2. ==> Python 3 support.

### ISSUE THREAD

**Issue by rolance** [IHTSDO/snomed-database-loader#47]
anydbm is not available in python-3

There is no option for Windows users to fallback to another dbm.

Falling back to python-2.7 in Windows with py2neo 3.1.2 breaks the entire project in neo4j 4.1.1 (http://localhost:7474/db/data returns 404 error).

-LHM

**Comment by kaicode** [comment]
The Neo4J implementation was updated in July 2023. Please try the new version. Closing this issue for now but feel free to reopen if there is still a problem.
