### ISSUE TITLE
Postgres copy failed to import whole data for description's term column that containing "

### ISSUE THREAD

**Issue by reinhardjs** [IHTSDO/snomed-database-loader#63]
I followed the import script outlined in the [PostgreSQL/load-postgresql.sql](https://github.com/IHTSDO/snomed-database-loader/blob/master/PostgreSQL/load-postgresql.sql) file and created a corresponding .sh script.

![image](https://github.com/user-attachments/assets/4b8441ea-d7af-4b44-9923-359d4ec1ebc6)

However, the import failed to load all the data because some columns in the term descriptions contained double quotes ("). `Antimikrobieller-Wirkstoff-r`
Below is the log output showing the error:

![image](https://github.com/user-attachments/assets/fa626b96-3122-4c30-a7c9-b1e704fc54a8)

I was working with the GermanyEdition release when this occurred.

I found that adding QUOTE E'\b' (to use backspace as the quote character) resolved the issue

![image](https://github.com/user-attachments/assets/b7af763f-d26d-45bf-8c73-f0be724e8f58)

Here is the full importer script I’ve re-created:
https://gist.github.com/reinhardjs/53d39dbd87390b8652899ffc9625dcf2

**Comment by kaicode** [comment]
Setting the quote character to backspace is a nice workaround to allow Postgres to ignore the quotes and just import them as part of the Description term value.

Thank you for this suggestion, I will add it to the standard Postgres import script in this repo.

**Comment by kaicode** [comment]
It looks like we are already using this solution in [some of the Postgres scripts](https://github.com/IHTSDO/snomed-database-loader/blob/d25786d/PostgreSQL/load_release-postgresql.sh#L92) but not others.

I've made it consistent now. I've also added UTF-8 encoding in some of the places where it was missing.

Thanks again for your contribution!
