### ISSUE TITLE
Error using postgres

### ISSUE THREAD

**Issue by acc4012** [IHTSDO/snomed-database-loader#9]
Hi, 

I got this error and don't know how to fix. Help me, please.

Generating loading script for 20170731
Password for user postgres:
psql:create-database-postgres.sql:5: NOTICE:  drop cascades to 12 other objects
DETAIL:  drop cascades to table snomedct.concept_f
drop cascades to table snomedct.description_f
drop cascades to table snomedct.textdefinition_f
drop cascades to table snomedct.relationship_f
drop cascades to table snomedct.stated_relationship_f
drop cascades to table snomedct.langrefset_f
drop cascades to table snomedct.associationrefset_f
drop cascades to table snomedct.attributevaluerefset_f
drop cascades to table snomedct.simplerefset_f
drop cascades to table snomedct.simplemaprefset_f
drop cascades to table snomedct.complexmaprefset_f
drop cascades to table snomedct.extendedmaprefset_f
DROP SCHEMA
CREATE SCHEMA
SET
SET
psql:environment-postgresql.sql:5: NOTICE:  table "concept_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:15: NOTICE:  table "description_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:29: NOTICE:  table "textdefinition_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:43: NOTICE:  table "relationship_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:58: NOTICE:  table "stated_relationship_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:73: NOTICE:  table "langrefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:85: NOTICE:  table "associationrefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:97: NOTICE:  table "attributevaluerefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:109: NOTICE:  table "simplerefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:120: NOTICE:  table "simplemaprefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:132: NOTICE:  table "complexmaprefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
psql:environment-postgresql.sql:149: NOTICE:  table "extendedmaprefset_f" does not exist, skipping
DROP TABLE
CREATE TABLE
SET
psql:tmp_loader.sql:7: ERROR:  relation "curr_concept_s" does not exist
psql:tmp_loader.sql:11: ERROR:  relation "curr_description_s" does not exist
psql:tmp_loader.sql:15: ERROR:  relation "curr_stated_relationship_s" does not exist
psql:tmp_loader.sql:19: ERROR:  relation "curr_relationship_s" does not exist
psql:tmp_loader.sql:23: ERROR:  relation "curr_textdefinition_s" does not exist
psql:tmp_loader.sql:27: ERROR:  relation "curr_attributevaluerefset_s" does not exist
psql:tmp_loader.sql:31: ERROR:  relation "curr_langrefset_s" does not exist
psql:tmp_loader.sql:35: ERROR:  relation "curr_associationrefset_s" does not exist

**Comment by siamchen** [comment]
Two things cause the problem:
1, The database table created is for "Full" which has the suffix of "_f". You need to change the suffix in the database creation file to "_s" for Snapshot.
2, The upload shell script still use the old naming convention. So, you need to remove the prefix of "curr_" in line 90 and make it looks like:
	echo -e "COPY ${tableName}" >> ${generatedLoadScript}
